### ISSUE TITLE
Mind your ps and qs

### ISSUE THREAD

**Issue by martinthomson** [chris-wood/draft-amjad-cfrg-partially-blind-rsa#23]
> a key pair MUST be the product of two safe primes p and q. A safe prime p is a prime number such that p = 2q + 1, where q is also a prime number

A lazy reader might infer that the values in the key pair have the relationship p=2q+1.  Consider using different labels for the definitional part to avoid this confusion.

**Comment by Guss123** [comment]
Oops did not get this reviewed by mistake but fixed the issue. Closing it now. Please re-open if needed.
